name: "Cargo Versions"

permissions:
  contents: "read"

on:
  workflow_dispatch:
  workflow_call:
    outputs:
      pkg-version:
        description: "Get release version"
        value: ${{ jobs.get-version.outputs.pkg-version }}
      rust-version:
        description: "Get release version"
        value: ${{ jobs.rust-version.outputs.rust-version }}

jobs:
  get-version:
    name: "Get release version"
    runs-on: "ubuntu-latest"
    outputs:
      pkg-version: ${{ steps.pkg-version.outputs.pkg-version }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get version"
        id: "pkg-version"
        shell: "bash"
        run: |
          PKG_VERSION=$(awk -F ' = ' '$1 ~ /^version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)
          echo "Cargo pkg-version=$PKG_VERSION"
          echo pkg-version=$PKG_VERSION >> $GITHUB_OUTPUT

  rust-version:
    name: "Get rust version"
    runs-on: "ubuntu-latest"
    outputs:
      rust-version: ${{ steps.rust-version.outputs.rust-version }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get rust version"
        id: "rust-version"
        shell: "bash"
        run: |
          RUST_VERSION=$(awk -F ' = ' '$1 ~ /^rust-version/ { gsub(/["]/, "", $2); printf("%s",$2) }' Cargo.toml)
          echo "Cargo rust-version=$RUST_VERSION"
          echo rust-version=$RUST_VERSION >> $GITHUB_OUTPUT
