name: "Workflow Orchestrator"

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]
  schedule:
    - cron: "05 05 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  get-DOM:
    uses: ./.github/workflows/get-DOM.yml

  docker-publish:
    needs: [get-DOM]
    uses: ./.github/workflows/docker-publish.yml
    with:
      latest: |
        ${{ ((github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
        github.event_name == 'workflow_dispatch' ||
        (needs.get-DOM.outputs.proceed == 'true' && github.event_name == 'schedule')) && 'true' || 'false' }}
    if: ${{ !cancelled() && !failure() }}
    permissions:
      contents: write
      packages: write
      id-token: write
    secrets: inherit
