name: "Workflow Orchestrator"

on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches: [main]
  schedule:
    - cron: "05 05 * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  get-DOM:
    uses: ./.github/workflows/get-DOM.yml

  bump-version:
    needs: [get-DOM]
    uses: ./.github/workflows/bump-version.yml
    with:
      proceed: ${{ needs.get-DOM.outputs.proceed }}
    # if: github.event_name == 'schedule'
    permissions:
      contents: write

  create-tag:
    needs: [get-DOM, bump-version]
    uses: ./.github/workflows/github-tag.yml
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch') ||
      (needs.get-DOM.outputs.proceed == 'true' && github.event_name == 'schedule')
    permissions:
      contents: write

  create-release:
    needs: [get-DOM, create-tag]
    uses: ./.github/workflows/github-release.yml
    if: |
      (github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
      (github.event_name == 'workflow_dispatch') ||
      (needs.get-DOM.outputs.proceed == 'true' && github.event_name == 'schedule')
    permissions:
      contents: write

  docker-publish:
    needs: [get-DOM, create-release]
    uses: ./.github/workflows/docker-publish.yml
    with:
      latest: |
        ${{ ((github.event_name == 'pull_request' && github.event.pull_request.merged == true) ||
        github.event_name == 'workflow_dispatch' ||
        (needs.get-DOM.outputs.proceed == 'true' && github.event_name == 'schedule')) && 'true' || 'false' }}
    permissions:
      contents: write
      packages: write
      id-token: write
